// Generated by geometry/generate_geo.py
SetFactory("Built-in");
Mesh.MshFileVersion = 2.2;
Mesh.Algorithm = 6;
Mesh.ElementOrder = 2;
Mesh.SecondOrderLinear = 0;
Mesh.HighOrderOptimize = 1;
Mesh.MeshSizeExtendFromBoundary = 0;
Mesh.MeshSizeFromPoints = 0;
// Curvature sizing is disabled: the r/c=0.001 nose otherwise triggers
// pathologically small 1-D sizes in Gmsh; the BL and distance fields
// explicitly control the required resolution.
Mesh.MeshSizeFromCurvature = 0;
hwall = 0.0001;
hbody = 0.02;
hnear = 0.08;
hfar = 1;
Rfar = 5;

// Rounded diamond: each vertex has incoming tangent, outgoing tangent, center.
Point(10) = {0.007046123433367668, 0.0009902680687415724, 0, hbody};
Point(11) = {0.007046123433367668, -0.0009902680687415724, 0, hbody};
Point(12) = {0.007185296534327732, 0, 0, hbody};
Point(13) = {0.4998608268990399, -0.07025085784741868, 0, hbody};
Point(14) = {0.50013917310096, -0.07025085784741868, 0, hbody};
Point(15) = {0.5, -0.06926058977867711, 0, hbody};
Point(16) = {0.9929538765666324, -0.0009902680687415724, 0, hbody};
Point(17) = {0.9929538765666324, 0.0009902680687415724, 0, hbody};
Point(18) = {0.9928147034656722, 0, 0, hbody};
Point(19) = {0.50013917310096, 0.07025085784741868, 0, hbody};
Point(20) = {0.4998608268990399, 0.07025085784741868, 0, hbody};
Point(21) = {0.5, 0.06926058977867711, 0, hbody};
Line(100) = {11, 13};
Circle(200) = {10, 12, 11};
Line(101) = {14, 16};
Circle(201) = {13, 15, 14};
Line(102) = {17, 19};
Circle(202) = {16, 18, 17};
Line(103) = {20, 10};
Circle(203) = {19, 21, 20};
Curve Loop(10) = {100, 201, 101, 202, 102, 203, 103, 200};

// Circular farfield centered at mid-chord.
Point(1000) = {0.5, 0, 0, hfar};
Point(1001) = {0.5 + Rfar, 0, 0, hfar};
Point(1002) = {0.5, Rfar, 0, hfar};
Point(1003) = {0.5 - Rfar, 0, 0, hfar};
Point(1004) = {0.5, -Rfar, 0, hfar};
Circle(300) = {1001, 1000, 1002};
Circle(301) = {1002, 1000, 1003};
Circle(302) = {1003, 1000, 1004};
Circle(303) = {1004, 1000, 1001};
Curve Loop(20) = {300, 301, 302, 303};
Plane Surface(100) = {20, 10};

// Stable physical IDs consumed by NekMesh and the session template.
Physical Curve(1) = {100, 101, 102, 103, 200, 201, 202, 203};
Physical Curve(2) = {300, 301, 302, 303};
Physical Surface(100) = {100};

// Tangential and isotropic near-body refinement outside the BL.
Field[1] = Distance;
Field[1].CurvesList = {100, 101, 102, 103, 200, 201, 202, 203};
Field[1].Sampling = 240;
Field[2] = Threshold;
Field[2].InField = 1;
Field[2].SizeMin = hbody;
Field[2].SizeMax = hnear;
Field[2].DistMin = 0;
Field[2].DistMax = 0.03;
Field[2].StopAtDistMax = 1;
Field[4] = Threshold;
Field[4].InField = 1;
Field[4].SizeMin = hnear;
Field[4].SizeMax = hfar;
Field[4].DistMin = 0.03;
Field[4].DistMax = 1.75;
Field[5] = Min;
Field[5].FieldsList = {2, 4};
Background Field = 5;

// Wall-normal layers; Quads=1 creates quads that extrude to hexahedra.
Field[3] = BoundaryLayer;
Field[3].CurvesList = {100, 101, 102, 103, 200, 201, 202, 203};
Field[3].Size = hwall;
Field[3].Ratio = 1.25;
Field[3].Thickness = 0.01;
Field[3].Quads = 1;
BoundaryLayer Field = 3;
