#!/usr/bin/env python3
"""Generate a Gmsh .geo file for the rounded Mach-3 diamond airfoil."""

from __future__ import annotations

import argparse
import math
from pathlib import Path


def unit(x: float, y: float) -> tuple[float, float]:
    n = math.hypot(x, y)
    return x / n, y / n


def rounded_vertices(radius: float):
    h = 0.5 * math.tan(math.radians(8.0))
    # Counter-clockwise polygon: LE, lower corner, TE, upper corner.
    vertices = [(0.0, 0.0), (0.5, -h), (1.0, 0.0), (0.5, h)]
    result = []
    for i, b in enumerate(vertices):
        a = vertices[(i - 1) % len(vertices)]
        c = vertices[(i + 1) % len(vertices)]
        u1 = unit(a[0] - b[0], a[1] - b[1])
        u2 = unit(c[0] - b[0], c[1] - b[1])
        phi = math.acos(max(-1.0, min(1.0, u1[0] * u2[0] + u1[1] * u2[1])))
        tangent_distance = radius / math.tan(phi / 2.0)
        center_distance = radius / math.sin(phi / 2.0)
        bisector = unit(u1[0] + u2[0], u1[1] + u2[1])
        incoming = (
            b[0] + tangent_distance * u1[0],
            b[1] + tangent_distance * u1[1],
        )
        outgoing = (
            b[0] + tangent_distance * u2[0],
            b[1] + tangent_distance * u2[1],
        )
        center = (
            b[0] + center_distance * bisector[0],
            b[1] + center_distance * bisector[1],
        )
        result.append((incoming, outgoing, center))
    return result


def build_geo(args: argparse.Namespace) -> str:
    fillets = rounded_vertices(args.radius)
    lines: list[str] = [
        '// Generated by geometry/generate_geo.py',
        'SetFactory("Built-in");',
        'Mesh.MshFileVersion = 2.2;',
        'Mesh.Algorithm = 6;',
        'Mesh.ElementOrder = 2;',
        'Mesh.SecondOrderLinear = 0;',
        'Mesh.HighOrderOptimize = 1;',
        'Mesh.MeshSizeExtendFromBoundary = 0;',
        'Mesh.MeshSizeFromPoints = 0;',
        '// Curvature sizing is disabled: the r/c=0.001 nose otherwise triggers',
        '// pathologically small 1-D sizes in Gmsh; the BL and distance fields',
        '// explicitly control the required resolution.',
        'Mesh.MeshSizeFromCurvature = 0;',
        f'hwall = {args.h_wall:.16g};',
        f'hbody = {args.h_body:.16g};',
        f'hnear = {args.h_near:.16g};',
        f'hfar = {args.h_far:.16g};',
        f'Rfar = {args.rfar:.16g};',
        '',
        '// Rounded diamond: each vertex has incoming tangent, outgoing tangent, center.',
    ]

    incoming_ids, outgoing_ids, center_ids = [], [], []
    for i, (incoming, outgoing, center) in enumerate(fillets):
        pin, pout, pc = 10 + 3 * i, 11 + 3 * i, 12 + 3 * i
        incoming_ids.append(pin)
        outgoing_ids.append(pout)
        center_ids.append(pc)
        lines.extend(
            [
                f'Point({pin}) = {{{incoming[0]:.16g}, {incoming[1]:.16g}, 0, hbody}};',
                f'Point({pout}) = {{{outgoing[0]:.16g}, {outgoing[1]:.16g}, 0, hbody}};',
                f'Point({pc}) = {{{center[0]:.16g}, {center[1]:.16g}, 0, hbody}};',
            ]
        )

    straight_ids, arc_ids = [], []
    for i in range(4):
        line_id, arc_id = 100 + i, 200 + i
        straight_ids.append(line_id)
        arc_ids.append(arc_id)
        nxt = (i + 1) % 4
        lines.append(f'Line({line_id}) = {{{outgoing_ids[i]}, {incoming_ids[nxt]}}};')
        lines.append(
            f'Circle({arc_id}) = {{{incoming_ids[i]}, {center_ids[i]}, {outgoing_ids[i]}}};'
        )

    airfoil_loop = []
    for i in range(4):
        airfoil_loop.extend([straight_ids[i], arc_ids[(i + 1) % 4]])
    airfoil_curves = straight_ids + arc_ids

    lines.extend(
        [
            f'Curve Loop(10) = {{{", ".join(map(str, airfoil_loop))}}};',
            '',
            '// Circular farfield centered at mid-chord.',
            'Point(1000) = {0.5, 0, 0, hfar};',
            'Point(1001) = {0.5 + Rfar, 0, 0, hfar};',
            'Point(1002) = {0.5, Rfar, 0, hfar};',
            'Point(1003) = {0.5 - Rfar, 0, 0, hfar};',
            'Point(1004) = {0.5, -Rfar, 0, hfar};',
            'Circle(300) = {1001, 1000, 1002};',
            'Circle(301) = {1002, 1000, 1003};',
            'Circle(302) = {1003, 1000, 1004};',
            'Circle(303) = {1004, 1000, 1001};',
            'Curve Loop(20) = {300, 301, 302, 303};',
            'Plane Surface(100) = {20, 10};',
            '',
            '// Stable physical IDs consumed by NekMesh and the session template.',
            f'Physical Curve(1) = {{{", ".join(map(str, airfoil_curves))}}};',
            'Physical Curve(2) = {300, 301, 302, 303};',
            'Physical Surface(100) = {100};',
            '',
            '// Tangential and isotropic near-body refinement outside the BL.',
            'Field[1] = Distance;',
            f'Field[1].CurvesList = {{{", ".join(map(str, airfoil_curves))}}};',
            'Field[1].Sampling = 240;',
            'Field[2] = Threshold;',
            'Field[2].InField = 1;',
            'Field[2].SizeMin = hbody;',
            'Field[2].SizeMax = hnear;',
            'Field[2].DistMin = 0;',
            f'Field[2].DistMax = {max(2.0 * args.bl_thickness, 0.03):.16g};',
            'Field[2].StopAtDistMax = 1;',
            'Field[4] = Threshold;',
            'Field[4].InField = 1;',
            'Field[4].SizeMin = hnear;',
            'Field[4].SizeMax = hfar;',
            f'Field[4].DistMin = {max(2.0 * args.bl_thickness, 0.03):.16g};',
            f'Field[4].DistMax = {min(0.35 * args.rfar, 3.0):.16g};',
            'Field[5] = Min;',
            'Field[5].FieldsList = {2, 4};',
            'Background Field = 5;',
            '',
            '// Wall-normal layers; Quads=1 creates quads that extrude to hexahedra.',
            'Field[3] = BoundaryLayer;',
            f'Field[3].CurvesList = {{{", ".join(map(str, airfoil_curves))}}};',
            'Field[3].Size = hwall;',
            f'Field[3].Ratio = {args.bl_ratio:.16g};',
            f'Field[3].Thickness = {args.bl_thickness:.16g};',
            'Field[3].Quads = 1;',
            'BoundaryLayer Field = 3;',
        ]
    )
    return '\n'.join(lines) + '\n'


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', required=True)
    parser.add_argument('--rfar', type=float, required=True)
    parser.add_argument('--radius', type=float, default=0.001)
    parser.add_argument('--h-wall', type=float, required=True)
    parser.add_argument('--bl-thickness', type=float, required=True)
    parser.add_argument('--bl-ratio', type=float, required=True)
    parser.add_argument('--h-body', type=float, required=True)
    parser.add_argument('--h-near', type=float, required=True)
    parser.add_argument('--h-far', type=float, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.radius <= 0 or args.radius >= 0.01:
        raise SystemExit('radius must be in (0, 0.01) chord')
    if args.rfar <= 2.0:
        raise SystemExit('rfar must exceed 2 chords')
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_geo(args), encoding='utf-8')
    print(output)


if __name__ == '__main__':
    main()
